### ISSUE TITLE
NullPointerException in io.swagger.v3.parser.OpenAPIV3Parser.read(String, List<AuthorizationValue>, ParseOptions) when no paths are present

### ISSUE THREAD

**Issue by garydgregory** [swagger-api/swagger-parser#1155]
NullPointerException in io.swagger.v3.parser.OpenAPIV3Parser.read(String, List<AuthorizationValue>, ParseOptions) no paths are present.
For example:
```
{
  "parameters": {
    "api-version": "2017-05-15",
    "subscriptionId": "d18d258f-bdba-4de1-8b51-e79d6c181d5e",
    "providerName": "Canonical"
  },
  "responses": {
    "200": {
      "body": [
        {
          "enabled": true,
          "supportPlanType": "standard",
          "willEmitOneTimeChargeIfReEnabled": true,
          "willEmitOneTimeChargeWhenEnabled": false
        },
        {
          "enabled": false,
          "supportPlanType": "advanced",
          "willEmitOneTimeChargeIfReEnabled": false,
          "willEmitOneTimeChargeWhenEnabled": true
        },
        {
          "enabled": false,
          "supportPlanType": "essential",
          "willEmitOneTimeChargeIfReEnabled": false,
          "willEmitOneTimeChargeWhenEnabled": false
        }
      ]
    }
  }
}
```
Causes:
```
java.lang.NullPointerException
	at io.swagger.v3.parser.OpenAPIV3Parser.read(OpenAPIV3Parser.java:91)
	at io.swagger.v3.parser.OpenAPIV3Parser.read(OpenAPIV3Parser.java:78)
...
```

**Comment by webron** [comment]
@garydgregory That does not look like a valid OAS3 definition...?

**Comment by garydgregory** [comment]
See https://github.com/swagger-api/swagger-parser/pull/1156.
There are definitions like this in Azure, which is where I found this.

**Comment by garydgregory** [comment]
You are right, never mind...
