### ISSUE TITLE
HTTP 401 even after adding AuthorizationValue in SwaggerParser().read()

### ISSUE THREAD

**Issue by sudarsunperu** [swagger-api/swagger-parser#1160]
I'm able to access the Swagger end point from Postman but when i try the same from ```new SwaggerParser().read()```, I get the following exception.

Note: The Readme also is not updated with the 3rd boolean parameter for  ```new SwaggerParser().read()```

```Server returned HTTP response code: 401 for URL: https://swaggerurl/v2/api-docs
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at io.swagger.parser.util.RemoteUrl.urlToString(RemoteUrl.java:138)
	at io.swagger.parser.Swagger20Parser.read(Swagger20Parser.java:93)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:79)
	at com.sudarsun.SwaggerParserTester.main(SwaggerParserTester.java:19)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://swaggerurl/v2/api-docs
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3051)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:300)
	at io.swagger.parser.util.RemoteUrl.urlToString(RemoteUrl.java:135)
	... 3 more```

**Comment by gracekarina** [comment]
Hi!, can you please send a test reproducing this issue, so we can work on a fix? thanks @sudarsunperu
