### ISSUE TITLE
Response `headers` are not deserialized correctly

### ISSUE THREAD

**Issue by xhh** [swagger-api/swagger-parser#118]
At [line 960 in SwaggerDeserializer.java](https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java#L960):

```java
Map<String, Property> headers = Json.mapper().convertValue(headersNode, Json.mapper().getTypeFactory().constructMapType(Map.class, String.class, Path.class));
```

It seems that the `Path` at the end of the line should be `Property` instead. Otherwise it causes an issue when generating code from the online petstore spec:

```shell
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i http://petstore.swagger.io/v2/swagger.json \
  -l java \
  -o petstore-java

...

Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: user
  Operation: loginUser
  Resource: get /user/login
  Definitions: {Order=io.swagger.models.ModelImpl@3d99bf08, Category=io.swagger.models.ModelImpl@b0b183eb, User=io.swagger.mode
ls.ModelImpl@41b446b7, Tag=io.swagger.models.ModelImpl@94631c47, Pet=io.swagger.models.ModelImpl@d82f2b78, ApiResponse=io.swagg
er.models.ModelImpl@b3e8918a}
        at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:530)
        at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:419)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:185)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.ClassCastException: io.swagger.models.Path cannot be cast to io.swagger.models.properties.Property
        at io.swagger.codegen.DefaultCodegen.addHeaders(DefaultCodegen.java:1344)
        at io.swagger.codegen.DefaultCodegen.fromResponse(DefaultCodegen.java:1097)
        at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:949)
        at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:474)
        ... 4 more
```

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-parser/commit/af128e2b61bf1bcf3e9a5120be558072c27bd49f
