### ISSUE TITLE
$ref path broken.

### ISSUE THREAD

**Issue by Nitwel** [swagger-api/swagger-parser#1381]
My file structure:
```
docs
  openapi.yaml
  paths
    activity
      activity.yaml
```
 Inside the activity.yaml, I have this as a reference but it doesn't work:
`$ref: '../../openapi.yaml#/components/parameters/Fields'`
In contrast, this does actually work:
```
$ref: '../openapi.yaml#/components/parameters/Fields'
or
$ref: 'openapi.yaml#/components/parameters/Fields'
```
Which doesn't make any sense.

Here is the error I get when using `$ref: '../../openapi.yaml#/components/parameters/Fields`:
<details>
  <summary>Error</summary>
  [main] WARN  io.swagger.v3.parser.OpenAPIV3Parser - Exception while reading:
java.lang.RuntimeException: Unable to load RELATIVE ref: ../../openapi.yaml path: C:\Users\nitwe\Documents\Programmieren\Directus\SDK-Generator
        at io.swagger.v3.parser.util.RefUtils.readExternalRef(RefUtils.java:239)
        at io.swagger.v3.parser.ResolverCache.loadRef(ResolverCache.java:119)
        at io.swagger.v3.parser.processors.ParameterProcessor.processParameters(ParameterProcessor.java:86)
        at io.swagger.v3.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:39)
        at io.swagger.v3.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:83)
        at io.swagger.v3.parser.OpenAPIResolver.resolve(OpenAPIResolver.java:49)
        at io.swagger.v3.parser.OpenAPIV3Parser.readLocation(OpenAPIV3Parser.java:67)
        at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:452)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:498)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:415)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
Caused by: java.lang.RuntimeException: Could not find ../../openapi.yaml on the classpath
        at io.swagger.v3.parser.util.ClasspathHelper.loadFileFromClasspath(ClasspathHelper.java:31)
        at io.swagger.v3.parser.util.RefUtils.readExternalRef(RefUtils.java:233)
        ... 11 common frames omitted
</details>

**Comment by DreadMonkey22** [comment]
Hello, I believe I have corrected this issue in the parser in the following repo: https://github.com/DreadMonkey22/swagger-parser/tree/kmk-fix-relative-path-issues.  In the RefUtils class I have introduced a Finder that will attempt to take any relative reference and resolve it based on the location of the OAS represented by the parentDirectory variable.  I have tested the two cases that were causing me problems for the openapi-generator project that uses this library.

1. ../ located in any $ref object.  The code was attempting to go up a directory from the location of the OAS and then resolve the reference.  In my case this was deep inside my model hierarchy so adding a reference from the OAS root would break integrations with Intellij.

2. $ref's that started with ./ but were buried deep in the Model hierarchy.  Again the code was looking relative to the initial OAS, so deep nested relative references were failing.

This is the first time I have fixed/pushed code to github and then posted for review before submitting a PR.  I believe this would fix the majority of community issues with relative references in OAS documents.
