### ISSUE TITLE
Dependency conflict with Spring boot

### ISSUE THREAD

**Issue by JJScrivener** [swagger-api/swagger-parser#1392]
Hi, I am working on a spring boot project and we want to parse swagger yaml files.

First I tried adding this dependency to my project

```
        <dependency>
            <groupId>io.swagger.parser.v3</groupId>
            <artifactId>swagger-parser</artifactId>
            <version>2.0.17</version>
        </dependency>
```

and then making a parser object as such
```
        OpenAPI openAPI = new OpenAPIV3Parser().read("./swagger.json");
```

but I keep getting this error thrown when it tries to make the object.

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonFactoryBuilder
	at io.swagger.v3.parser.ObjectMapperFactory.createJsonFactory(ObjectMapperFactory.java:41)
	at io.swagger.v3.parser.ObjectMapperFactory.createJson(ObjectMapperFactory.java:18)
	at io.swagger.v3.parser.ObjectMapperFactory.createJson(ObjectMapperFactory.java:14)
	at io.swagger.v3.parser.OpenAPIV3Parser.<clinit>(OpenAPIV3Parser.java:38)
	at io.datallama.api.SwaggerTest.main(SwaggerTest.java:11)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonFactoryBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```

Then what I did is I found a project on git hub that was already working ([https://github.com/kalaspuffar/swagger-reader.git](https://github.com/kalaspuffar/swagger-reader.git)) and when I added the swing parent to his pom file I started getting the same error that is in my project.

```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.5.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
```

Has anyone encountered this before or know how to fix it?

**Comment by GrinDeN** [comment]
Same error here but also for newer, 2.0.20 version

**Comment by rivancic** [comment]
I guess you need to bump the version of jackson core in your project.
JsonFactoryBuilder only exists in jackson-core 2.10 and higher

Check out the following issue: https://github.com/swagger-api/swagger-parser/issues/1365

**Comment by kyao233** [comment]
Some error encountered, downgrade to 2.0.16 works well for me.
