### ISSUE TITLE
Unit test fails because relative file URLs are not legal

### ISSUE THREAD

**Issue by garydgregory** [swagger-api/swagger-parser#152]
With master I get:

```
Configuring TestNG with: TestNG652Configurator
Tests run: 82, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.381 sec <<< FAILURE! - in TestSuite
readUberApiFromFile(io.swagger.parser.SwaggerReaderTest)  Time elapsed: 0.02 sec  <<< FAILURE!
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file://src/test/resources/uber.json
        at java.nio.file.Paths.get(Paths.java:84)
        at io.swagger.parser.util.PathUtils.getParentDirectoryOfFile(PathUtils.java:9)
        at io.swagger.parser.ResolverCache.<init>(ResolverCache.java:54)
        at io.swagger.parser.SwaggerResolver.<init>(SwaggerResolver.java:26)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:52)
        at io.swagger.parser.SwaggerReaderTest.readUberApiFromFile(SwaggerReaderTest.java:19)
```

Patch:

```
diff --git a/modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerReaderTest.java b/modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerReaderTest.java
index 72cea55..ec973d2 100644
--- a/modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerReaderTest.java
+++ b/modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerReaderTest.java
@@ -16,7 +16,7 @@
     @Test(description = "it should read the uber api with file protocol")
     public void readUberApiFromFile() {
         final SwaggerParser parser = new SwaggerParser();
-        final Swagger swagger = parser.read("file://src/test/resources/uber.json");
+        final Swagger swagger = parser.read("src/test/resources/uber.json");
         assertNotNull(swagger);
     }
```

Using:

```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: E:\Java\apache-maven-3.3.9
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_65\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```

**Comment by fehguy** [comment]
File protocol should be legal in path, even for windows?

**Comment by garydgregory** [comment]
But _relative_ file URLs are tricky to get right.

**Comment by fehguy** [comment]
I totally agree

**Comment by garydgregory** [comment]
Is there a separate test that validates that the "file" scheme works?

**Comment by fehguy** [comment]
This should be fixed
