### ISSUE TITLE
I use

### ISSUE THREAD

**Issue by CaseCy** [swagger-api/swagger-parser#1548]
I use it to parse swagger json
```java
Swagger swagger = new SwaggerParser().read(jsonNode,true);
```
but
```java
Exception in thread "main" java.lang.NoSuchMethodError: io.swagger.models.Response.getResponseSchema()Lio/swagger/models/Model;
	at io.swagger.parser.processors.ResponseProcessor.processResponse(ResponseProcessor.java:25)
	at io.swagger.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:47)
```
if i write like this
```java
Swagger swagger = new SwaggerParser().read(jsonNode,false);
```
there is no error
but the response schema is null

**Comment by CaseCy** [comment]
I solve the problem, i use
```xml
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger2</artifactId>
    <version>2.9.2</version>
</dependency>
```
and
```
<dependency>
    <groupId>io.swagger.parser.v3</groupId>
    <artifactId>swagger-parser</artifactId>
    <version>2.0.24</version>
</dependency>
```
both in same project ,so it may conflict , it works right when i remove springfox-swagger2
