### ISSUE TITLE
Parsing Swagger 2.0 file results in an error

### ISSUE THREAD

**Issue by rheda-atlassian** [swagger-api/swagger-parser#1618]
Parsing Swagger 2.0 file results in an error with "java.lang.NoClassDefFoundError: io/swagger/models/Responses"

Here is the url: https://id-external-directory-api.prod.atl-paas.net/api/swagger.json

Here is the full stack trace:

```
java.lang.NoClassDefFoundError: io/swagger/models/Responses

	at io.swagger.parser.util.SwaggerDeserializer.responses(SwaggerDeserializer.java:1158)
	at io.swagger.parser.util.SwaggerDeserializer.operation(SwaggerDeserializer.java:399)
	at io.swagger.parser.util.SwaggerDeserializer.path(SwaggerDeserializer.java:296)
	at io.swagger.parser.util.SwaggerDeserializer.paths(SwaggerDeserializer.java:191)
	at io.swagger.parser.util.SwaggerDeserializer.parseRoot(SwaggerDeserializer.java:111)
	at io.swagger.parser.util.SwaggerDeserializer.deserialize(SwaggerDeserializer.java:41)
	at io.swagger.parser.Swagger20Parser.convertToSwagger(Swagger20Parser.java:142)
	at io.swagger.parser.Swagger20Parser.read(Swagger20Parser.java:111)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:77)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:60)
	at io.atlassian.identity.ieda.apitracing.service.SwaggerParserServiceImpl.parseSwagger(SwaggerParserServiceImpl.java:25)
	at io.atlassian.identity.ieda.apitracing.SwaggerParserServiceImplTest.test(SwaggerParserServiceImplTest.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:55)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:41)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.ClassNotFoundException: io.swagger.models.Responses
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	
```

![image](https://user-images.githubusercontent.com/57893708/136675316-954f13ff-3158-4817-a0f7-bb0f2187bf93.png)

**Comment by gracekarina** [comment]
Hi @rheda-atlassian  I can't access the link, please attach the file here or provide a new one. Thanks

**Comment by gunnarvelle** [comment]
Hi @rheda-atlassian! 

The problem can be that you probably have an old version of swagger-models in your application.
I have an application where I use springfox to generate own swagger-docs, and that depends on swagger-models:1.5.20. If you add a newer version, for instance swagger-models:1.6.3 to your dependencies, this will solve your issues.

Regards

**Comment by gbwxy** [comment]
Hi @rheda-atlassian  The problem can be that you project dependency io.springfox:springfox-boot-starter:jar:3.0.0 or   io.springfox:springfox-swagger2:jar:3.0.0, this jar cloud  io.swagger:swagger-models:jar:1.5.20

![image](https://user-images.githubusercontent.com/64130992/159227393-9522d5dd-1332-453d-9794-fa5bbaea7a63.png)

you may solve the problem by excloud swagger-models:1.5.20 like this

`        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-boot-starter</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.swagger.parser.v3</groupId>
            <artifactId>swagger-parser</artifactId>
            <version>2.0.31</version>
        </dependency>

        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-models</artifactId>
            <version>1.6.5</version>
        </dependency>
`

**Comment by michaelwangwangwang** [comment]
how can resolve it?

**Comment by michaelwangwangwang** [comment]
> 

you are right

**Comment by frantuma** [comment]
Closing this issue as solved, please reopen if still experiencing issues
