### ISSUE TITLE
swagger-parser exception handler crash

### ISSUE THREAD

**Issue by jtpereyda** [swagger-api/swagger-parser#1638]
Second exception is generated for particular error cases. This issue was found by fuzzing with jazzer, but does not have any known security implications.

Demo file:
```
import io.swagger.v3.parser.OpenAPIV3Parser;
import java.nio.charset.StandardCharsets;
import java.util.Base64;

public class SwaggerParserExceptionHandlerCrash {
    public static void main(String[] args) {
        OpenAPIV3Parser parser = new OpenAPIV3Parser();
        String data = "\ufeff{\"openapi\":\"3.1%0\",a%,a%";
        parser.readContents(data, null, null);
    }
}
```

Execution and output:
```
> java -cp swagger-parser/modules/swagger-parser/target/lib/*:swagger-parser/modules/swagger-parser-core/target/swagger-parser-core-2.0.29-SNAPSHOT.jar:swagger-parser/modules/swagger-parser-v3/target/swagger-parser-v3-2.0.29-SNAPSHOT.jar:swagger-parser/modules/swagger-parser/target/swagger-parser-2.0.29-SNAPSHOT.jar:. SwaggerParserExceptionHandlerCrash
[main] WARN io.swagger.v3.parser.OpenAPIV3Parser - Exception while parsing:
com.fasterxml.jackson.core.JsonParseException: Duplicate field 'a%'
 at [Source: (StringReader); line: 1, column: 25]
	at com.fasterxml.jackson.core.json.JsonReadContext._checkDup(JsonReadContext.java:212)
	at com.fasterxml.jackson.core.json.JsonReadContext.setCurrentName(JsonReadContext.java:206)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:456)
	at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:986)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:269)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:16)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4635)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3042)
	at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:154)
	at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:99)
	at SwaggerParserExceptionHandlerCrash.main(SwaggerParserExceptionHandlerCrash.java:9)
Exception in thread "main" java.util.UnknownFormatConversionException: Conversion = '''
	at java.util.Formatter.checkText(Formatter.java:2579)
	at java.util.Formatter.parse(Formatter.java:2555)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at io.swagger.v3.parser.OpenAPIV3Parser.getParseErrorMessage(OpenAPIV3Parser.java:209)
	at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:167)
	at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:99)
	at SwaggerParserExceptionHandlerCrash.main(SwaggerParserExceptionHandlerCrash.java:9)
```

Root cause: https://github.com/swagger-api/swagger-parser/blob/19bc11c8a60421956711a04bad35603ee12d3daa/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/OpenAPIV3Parser.java#L209

`originalMessage` is an error message from another library, which contains a user controlled string, which can cause errors with string formatting. Suggested fix:

```
            return String.format("%s in `%s`", originalMessage, location);
```

Exception message after this fix:

```
> java -cp swagger-parser/modules/swagger-parser/target/lib/*:swagger-parser/modules/swagger-parser-core/target/swagger-parser-core-2.0.29-SNAPSHOT.jar:swagger-parser/modules/swagger-parser-v3/target/swagger-parser-v3-2.0.29-SNAPSHOT.jar:swagger-parser/modules/swagger-parser/target/swagger-parser-2.0.29-SNAPSHOT.jar:. SwaggerParserExceptionHandlerCrash
[main] WARN io.swagger.v3.parser.OpenAPIV3Parser - Exception while parsing:
com.fasterxml.jackson.core.JsonParseException: Duplicate field 'a%'
 at [Source: (StringReader); line: 1, column: 25]
	at com.fasterxml.jackson.core.json.JsonReadContext._checkDup(JsonReadContext.java:212)
	at com.fasterxml.jackson.core.json.JsonReadContext.setCurrentName(JsonReadContext.java:206)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:456)
	at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:986)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:269)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:16)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4635)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3042)
	at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:154)
	at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:99)
	at SwaggerParserExceptionHandlerCrash.main(SwaggerParserExceptionHandlerCrash.java:9)
```

**Comment by gracekarina** [comment]
thanks @jtpereyda
