### ISSUE TITLE
ExternalRefProcessor: java.lang.StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by JukkaOravasaari** [swagger-api/swagger-parser#1658]
I'm seeing the following exception with swagger-parser 2.0.30 (I also know that it used to repro (at least) with 2.0.28 but not with 2.0.20):

]2022-02-10 06:11:56,628 [WARN] from [io.swagger.v3.parser.OpenAPIV3Parser] [] - [Exception while resolving:]
[java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefToExternalSchema(ExternalRefProcessor.java:128)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefToExternalSchema(ExternalRefProcessor.java:139)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefSchema(ExternalRefProcessor.java:934)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processSchema(ExternalRefProcessor.java:222)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processProperties(ExternalRefProcessor.java:245)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processProperties(ExternalRefProcessor.java:252)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processSchema(ExternalRefProcessor.java:225)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processProperties(ExternalRefProcessor.java:245)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processSchema(ExternalRefProcessor.java:235)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefSchemaObject(ExternalRefProcessor.java:896)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefToExternalPathItem(ExternalRefProcessor.java:302)
	at io.swagger.v3.parser.processors.PathsProcessor.processReferencePath(PathsProcessor.java:313)
	at io.swagger.v3.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:63)
	at io.swagger.v3.parser.OpenAPIResolver.resolve(OpenAPIResolver.java:49)
	at io.swagger.v3.parser.OpenAPIV3Parser.resolve(OpenAPIV3Parser.java:183)
	at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:162)
	at io.swagger.v3.parser.OpenAPIV3Parser.readLocation(OpenAPIV3Parser.java:89)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)

`
public class MyClass {

    public static void main(String args[]) {

      String refWithoutFile = "#/components/schemas/abc";

      String refWithFile = "./abc.yaml#/paths/myPath";

      System.out.println("with file: " + refWithFile.split("#/")[0]);

      System.out.println("without file: " + refWithoutFile.split("#/")[0]);
    }
}
`

`
with file: ./abc.yaml

without file: 
`

**Comment by JukkaOravasaari** [comment]
To me it seems root cause is covered by non-merged PR: https://github.com/swagger-api/swagger-parser/pull/1634

**Comment by gracekarina** [comment]
https://github.com/swagger-api/swagger-parser/commit/2ec8ebb650014b6d9614853eaa07b8d3f884f6a2

**Comment by gracekarina** [comment]
fixed by https://github.com/swagger-api/swagger-parser/pull/1672
