### ISSUE TITLE
It is impossible to parse local file under Windows with location defined as correct URL/URI.

### ISSUE THREAD

**Issue by kendzi** [swagger-api/swagger-parser#176]
Lets assume we have correct swagger json file under that windows location:
`E:/tmp/swagger.json`

Lets try to load it using parser, but location defined as correct url/uri:

```
new Swagger20Parser().read(location, null)
```

The file location converted into:
1) The correct url:

```
String location = "file:/E:/tmp/swagger.json";
```

2) The correct uri (with empty host name):

```
String location = "file:///E:/tmp/swagger.json";
```

Unfortunately both of location falls to loads.

1) The error during load of URL

```
reading from file:/E:/tmp/swagger.json
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/E:/tmp/swagger.json
    at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
    at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
    at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
    at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
    at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
    at java.nio.file.Paths.get(Paths.java:84)
    at io.swagger.parser.Swagger20Parser.read(Swagger20Parser.java:80)
    at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:64)
    at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:52)
    ...
```

2) The error during load of URL

```
reading from file:///E:/tmp/swagger.json
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /E:/tmp/swagger.json
    at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
    at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
    at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
    at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
    at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
    at java.nio.file.Paths.get(Paths.java:84)
    at io.swagger.parser.Swagger20Parser.read(Swagger20Parser.java:80)
    at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:64)
    at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:52)
    ...
```

**Comment by fehguy** [comment]
Consider a PR.
