### ISSUE TITLE
Parsing Swagger Doc with `paths` as Array of JSON Objects?

### ISSUE THREAD

**Issue by kevinmeredith** [swagger-api/swagger-parser#197]
The V2 [paths](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#paths-object) spec defines that `paths` as a [JSON Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#paths-object-example).

Note that the following JSON has an array of JSON Objects for its `paths` key:

```
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Simple API"
  },
  "host": "httpbin.org",
  "basePath": "/",
  "produces": [
    "application/json"
  ],
  "paths": [ {
    "/get": {
      "get": {
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
  ]
}
```

Observe the difference in behavior between: v `1.0.10` and `1.0.17`:

### 1.0.10

```
$cat build.sbt
 libraryDependencies += "io.swagger" % "swagger-parser" % "1.0.10"
$sbt console
scala> new Swagger20Parser().parse("""
     | {
     |   "swagger": "2.0",
     |   "info": {
     |     "version": "1.0.0",
     |     "title": "Simple API"
     |   },
     |   "host": "httpbin.org",
     |   "basePath": "/",
     |   "produces": [
     |     "application/json"
     |   ],
     |   "paths": [ {
     |     "/get": {
     |       "get": {
     |         "responses": {
     |           "200": {
     |             "description": "OK"
     |           }
     |         }
     |       }
     |     }
     |   }
     |   ]
     | }
     | """)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.IllegalArgumentException: Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1] (through reference chain: io.swagger.models.Swagger["paths"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:2774)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:2700)
	at io.swagger.parser.Swagger20Parser.convertToSwagger(Swagger20Parser.java:56)

```

### 1.0.17

```
$cat build.sbt
 libraryDependencies += "io.swagger" % "swagger-parser" % "1.0.17"
$sbt console
scala> new Swagger20Parser().parse("""
     | {
     |   "swagger": "2.0",
     |   "info": {
     |     "version": "1.0.0",
     |     "title": "Simple API"
     |   },
     |   "host": "httpbin.org",
     |   "basePath": "/",
     |   "produces": [
     |     "application/json"
     |   ],
     |   "paths": [ {
     |     "/get": {
     |       "get": {
     |         "responses": {
     |           "200": {
     |             "description": "OK"
     |           }
     |         }
     |       }
     |     }
     |   }
     |   ]
     | }
     | """)
res2: io.swagger.models.Swagger = io.swagger.models.Swagger@6839ffc3

scala> res2.getPaths
res3: java.util.Map[String,io.swagger.models.Path] = null
```

Perhaps a philosophical difference took hold between these 2 versions?

Note that I found this behavior when upgrading from `1.0.10` to `1.0.17`.

**Comment by fehguy** [comment]
well paths are not arrays, they're objects.  The newer parser should emit a warning that the type was not expected.
