### ISSUE TITLE
Better parser error message with $ref

### ISSUE THREAD

**Issue by Kabhal** [swagger-api/swagger-parser#200]
When a parser error occurs with a swagger file including some external files, referenced with $ref, the error message does not specify the $ref in error.

It just specify 'string', e.g.: 
```
while scanning a simple key; could not found expected ':';  in 'string', line 10, column 3:
      tags:
      ^
```

If you have a lot of $ref, it's very hard to locate the problem.

**Comment by fehguy** [comment]
Hi, can you please send more details?

**Comment by Kabhal** [comment]
swagger.yaml :
```
swagger: "2.0"
info:
  title: Service API
host: host.domain.com
paths:
  /actions/launch:
    $ref: ./launch.yaml
```

launch.yaml:
```
post:
  summary:Summary without leading space
  description: Launch command
```

```
mapping values are not allowed here
 in 'string', line 3, column 14:
      description: Launch command
                 ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:159)
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:400)
	at io.swagger.parser.util.DeserializationUtils.readYamlValue(DeserializationUtils.java:67)
	at io.swagger.parser.util.DeserializationUtils.deserialize(DeserializationUtils.java:46)
	at io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:96)
	at io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:55)
	at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:41)
        ...
```

**Comment by Kabhal** [comment]
Another kind of errors without $ref location :

Some resources to reproduce the message :

swagger.yaml :
```
swagger: "2.0"
info:
  title: Service API
host: host.domain.com
paths:
  /actions/launch:
    $ref: ./launch.yaml
```

launch.yaml:
```
post:
  description:Launch command without leading space, and no summary
```

```
Exception in thread "main" java.lang.IllegalArgumentException: Can not instantiate value of type [simple type, class io.swagger.models.Operation] from String value ('description:Description'); no single-String constructor/factory method
 at [Source: N/A; line: -1, column: -1] (through reference chain: io.swagger.models.Path["post"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:2774)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:2700)
	at io.swagger.util.PathDeserializer.deserialize(PathDeserializer.java:27)
	at io.swagger.util.PathDeserializer.deserialize(PathDeserializer.java:14)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:2769)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:2700)
	at io.swagger.parser.util.DeserializationUtils.readYamlValue(DeserializationUtils.java:67)
	at io.swagger.parser.util.DeserializationUtils.deserialize(DeserializationUtils.java:46)
	at io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:96)
	at io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:55)
	at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:41)
        ...
```

**Comment by fehguy** [comment]
OK since this is invalid YAML, i'm not going to prioritize fixing it.  Per YAML specification, you must have a space after the comma (see `2.1. Collections` in the [1.2 specification](http://yaml.org/spec/1.2/spec.html)).
