### ISSUE TITLE
NPE at ResponseProcessor.java:20

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-parser#211]
To repeat the issue, pls run the following with codegen:
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
>   -i https://api.luno.io/swagger.json \
>   -l perl \
>   -o /tmp/client/
reading from https://api.luno.io/swagger.json
Exception in thread "main" java.lang.NullPointerException
    at io.swagger.parser.processors.ResponseProcessor.processResponse(ResponseProcessor.java:20)
    at io.swagger.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:44)
    at io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:72)
    at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:41)
    at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
    at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:339)
    at io.swagger.codegen.cmd.Generate.run(Generate.java:193)
    at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
```

Spec to reproduce the issue: https://api.luno.io/swagger.json

Ref: https://github.com/swagger-api/swagger-codegen/issues/2331

**Comment by fehguy** [comment]
Looks like the SwaggerResolver is mistaking a response vendor extension for a response object.

**Comment by fehguy** [comment]
See https://github.com/swagger-api/swagger-core/issues/1725

**Comment by fehguy** [comment]
Fixed by https://github.com/swagger-api/swagger-parser/commit/682a0224eeae97eb405f02b02544ad9cc61688c7
