### ISSUE TITLE
[Question] Disable Log/Print Statements?

### ISSUE THREAD

**Issue by kevinmeredith** [swagger-api/swagger-parser#244]
Given:

```
scala> import io.swagger.parser._
import io.swagger.parser._

// attempt to read URL hosted on private network
// note that, when I made this call, I was on this private network 
scala> new SwaggerParser().parse($PRIVATE_SWAGGER_DOC)
java.net.UnknownHostException: $PRIVATE_SWAGGER_DOC
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at java.net.Socket.connect(Socket.java:538)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
    at sun.net.www.http.HttpClient.New(HttpClient.java:308)
    at sun.net.www.http.HttpClient.New(HttpClient.java:326)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932)
    at io.swagger.parser.util.RemoteUrl.urlToString(RemoteUrl.java:129)
    at io.swagger.parser.Swagger20Parser.read(Swagger20Parser.java:81)
    at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:64)
    at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:52)
```

When using this library from my web service, it's annoying to me to view this print output.

It seems to me that this [line of code](https://github.com/swagger-api/swagger-parser/blob/d0894a334213d05bd64d573c233d48168f4b551a/modules/swagger-parser/src/main/java/io/swagger/parser/util/RemoteUrl.java#L155) is responsible.

Is there then no way to disable these print statements upon errors?

**Comment by kevinmeredith** [comment]
Hi - just respectfully pinging here to request some feedback on this issue.

Thanks

**Comment by wing328** [comment]
@kevinmeredith what about capturing the stack trace with LOGGER.error instead?

**Comment by kevinmeredith** [comment]
@wing328, please correct me if I'm wrong, but isn't the above [LOC](https://github.com/swagger-api/swagger-parser/blob/d0894a334213d05bd64d573c233d48168f4b551a/modules/swagger-parser/src/main/java/io/swagger/parser/util/RemoteUrl.java#L155):

`e.printStackTrace();`

responsible for the above print output in this issue's first comment?

In other words, it's not clear to me how changing the LOG level will impact `e.printStackTrace`.

**Comment by wing328** [comment]
Sorry I was not clear. For my suggested solution, I'll get rid of `e.printStackTrace` (the line that you pointed out and there are a couple others).

For the stack trace message, we can convert it to a string and then log with LOGGER.error.

**Comment by kevinmeredith** [comment]
Sounds good to me, @wing328. Let me know if you'd like a PR or if you'll handle it.

Thanks

**Comment by wing328** [comment]
If you've time, I wonder if you can submit a PR.

(I'm not in charge of this project although I've a few PRs merged before)
