### ISSUE TITLE
NPE parsing referenced path parameters

### ISSUE THREAD

**Issue by diegode** [swagger-api/swagger-parser#268]
This test is failing in master (I added it in `SwaggerParserTest`):

    @Test
    public void testParseRefPathParameters() throws Exception {
        String yaml =
                "swagger: '2.0'\n" +
                "info:\n" +
                "  title: test\n" +
                "  version: '0.0.0'\n" +
                "parameters:\n" +
                "  report-id:\n" +
                "    name: id\n" +
                "    in: path\n" +
                "    type: string\n" +
                "    required: true\n" +
                "paths:\n" +
                "  /reports/{id}:\n" +
                "    parameters:\n" +
                "        - $ref: '#/parameters/report-id'\n" +
                "    put:\n" +
                "      parameters:\n" +
                "        - name: id\n" +
                "          in: body\n" +
                "          required: true\n" +
                "          schema:\n" +
                "            $ref: '#/definitions/report'\n" +
                "      responses:\n" +
                "        200:\n" +
                "          description: ok\n" +
                "definitions:\n" +
                "  report:\n" +
                "    type: object\n" +
                "    properties:\n" +
                "      id:\n" +
                "        type: string\n" +
                "      name:\n" +
                "        type: string\n" +
                "    required:\n" +
                "    - id\n" +
                "    - name\n";
        SwaggerParser parser = new SwaggerParser();
        Swagger swagger = parser.parse(yaml);
    }

The NPE is:

>   java.lang.NullPointerException
>     at io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:54)
>     at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:40)
>     at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:119)
>     at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:111)
>     at io.swagger.parser.SwaggerParserTest.testParseRefPathParameters(SwaggerParserTest.java:132)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
> 

It seems it's a bug introduced here: https://github.com/swagger-api/swagger-parser/commit/61bcab026a0775c630b885c9f7874430f5161c4b

**Comment by diegode** [comment]
We can close this already.
