### ISSUE TITLE
[Java] importMappings not working with external classes

### ISSUE THREAD

**Issue by brentryan** [swagger-api/swagger-parser#302]
You wind up with an error stack trace like this:
```
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution event-snapshot-builder-java-client of goal io.swagger:swagger-codegen-maven-plugin:2.3.0-SNAPSHOT:generate failed: Could not find definitions/FooType in contents of ./definitions/foo.yaml
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.RuntimeException: Could not find definitions/FooType in contents of ./definitions/foo.yaml
	at io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:118)
	at io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(ExternalRefProcessor.java:30)
	at io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(ExternalRefProcessor.java:71)
	at io.swagger.parser.processors.ModelProcessor.processRefModel(ModelProcessor.java:92)
	at io.swagger.parser.processors.ModelProcessor.processModel(ModelProcessor.java:33)
	at io.swagger.parser.processors.DefinitionsProcessor.processDefinitions(DefinitionsProcessor.java:40)
	at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:41)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:391)
	at io.swagger.codegen.plugin.CodeGenMojo.execute(CodeGenMojo.java:276)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

See for more details: https://groups.google.com/forum/#!topic/swagger-swaggersocket/YE1byLCQv5c

FWIW, I tried 1.0.21 of SwaggerParser and this part works, but a different issue is broken.  On 1.0.21 the problem is collections do NOT provide the imports properly from import-mappings.

**Comment by fehguy** [comment]
This is for swagger-codegen.
