### ISSUE TITLE
Relative references from a file in a sub-folder to other folders do not resolve

### ISSUE THREAD

**Issue by KaelenProctor** [swagger-api/swagger-parser#305]
Originally from swagger-codegen https://github.com/swagger-api/swagger-codegen/issues/3614

If you have a directory structure like
```
swagger.yaml
-folder1
 -file1.yaml
 -folder2
  -file2.yaml
-folder3
 -file3.yaml
```
then from file1.yaml it is unable to resolve references to file3.yaml or file2.yaml.

For the case in which file1 references file2, the exception thrown is:
```
Exception in thread "main" java.lang.RuntimeException: Unable to load RELATIVE ref: ../folder2/file2.yaml
        at io.swagger.parser.util.RefUtils.readExternalRef(RefUtils.java:140)
        at io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:96)
        at io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(ExternalRefProcessor.java:30)
        at io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(ExternalRefProcessor.java:69)
        at io.swagger.parser.processors.PropertyProcessor.processRefProperty(PropertyProcessor.java:33)
        at io.swagger.parser.processors.PropertyProcessor.processProperty(PropertyProcessor.java:21)
        at io.swagger.parser.processors.PropertyProcessor.processObjectProperty(PropertyProcessor.java:59)
        at io.swagger.parser.processors.PropertyProcessor.processProperty(PropertyProcessor.java:27)
        at io.swagger.parser.processors.ResponseProcessor.processResponse(ResponseProcessor.java:21)
        at io.swagger.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:45)
        at io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:89)
        at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:40)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
        at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:390)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:221)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: java.lang.RuntimeException: Could not find ../folder2/file2.yaml on the classpath
        at io.swagger.parser.util.ClasspathHelper.loadFileFromClasspath(ClasspathHelper.java:31)
        at io.swagger.parser.util.RefUtils.readExternalRef(RefUtils.java:135)
        ... 15 more
```

I created a suite of tests that I believe illustrate the problem, and attached it [swagger-relative-file-references.zip](https://github.com/swagger-api/swagger-parser/files/548638/swagger-relative-file-references.zip).

The test cases that compare "./file1.yaml" vs "file.yaml" can likely be ignored, I created them for my own education to verify which formats of a relative reference were acceptable.

**Comment by fehguy** [comment]
Thank you for submitting this.  Are you testing with master or the latest release?

**Comment by fehguy** [comment]
In the future, consider sending a PR with failing tests.  Then we're all testing the same thing.  But since you did organize your tests, here is my test feedback:

- [X] Case 1 Passes with existing master
- [X] Case 2 Passes with #307
- [ ] Case 3
- [ ] Case 4
- [ ] Case 5
- [ ] Case 6
- [ ] Case 7
- [ ] Case 8
- [ ] Case 9
- [ ] Case 10
- [ ] Case 11

**Comment by KaelenProctor** [comment]
@fehguy These cases were tested with release 2.2.1 of swagger-codegen. I've also tested with a more recent master version, 4f9ee0f93de77c9d31acf73ef60a0ee2c5f9872f to be specific, and the same behaviour occurs.

I was planning on making a PR soon, but I haven't written Java in several years so I have a bit of ramping up to do =)

**Comment by KaelenProctor** [comment]
This was tested with the latest release, 2.2.1. I can re-run the test cases
with master tomorrow but from my initial testing with master last week the
same issues were occurring.

**Comment by fehguy** [comment]
So thank you for getting these tests in.  It was a long time coming, and I've gone through and carefully recreated your scenarios.  This will go in the next parser release, then into codegen.

**Comment by maheshmahadevan** [comment]
Has this been fixed , i am still facing the problem with swagger-codegen v2.3.0
