### ISSUE TITLE
Swagger parser fail to parse the v2.0 example specification

### ISSUE THREAD

**Issue by bertrand-quenin** [swagger-api/swagger-parser#35]
Hi,

I'm testing swagger-codegen with the reference specification example (`https://raw.githubusercontent.com/swagger-api/swagger-spec/master/examples/v2.0/yaml/petstore.yaml`) and it seems it's not working:

```
~/w/swagger-codegen ❯❯❯ java -jar modules/swagger-codegen-distribution/target/swagger-codegen-distribution-2.1.2-M1.jar -l java -i https://raw.githubusercontent.com/swagger-api/swagger-spec/master/examples/v2.0/yaml/petstore.yaml
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
reading from https://raw.githubusercontent.com/swagger-api/swagger-spec/master/examples/v2.0/yaml/petstore.yaml
while parsing a block mapping; expected <block end>, but found Scalar;  in 'reader', line 1, column 15:
    swagger: "2.0"info:  version: 1.0.0  title: Sw ... 
                  ^
reading from https://raw.githubusercontent.com/swagger-api/swagger-spec/master/examples/v2.0/yaml/petstore.yaml
while parsing a block mapping; expected <block end>, but found Scalar;  in 'reader', line 1, column 15:
    swagger: "2.0"info:  version: 1.0.0  title: Sw ... 
                  ^
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'swagger': was expecting ('true', 'false' or 'null')
 at [Source: swagger: "2.0"info:  version: 1.0.0  title: Swagger Petstore  license:    name: MIThost: petstore.swagger.wordnik.combasePath: /v1schemes:  - httpconsumes:  - application/jsonproduces:  - application/jsonpaths:  /pets:    get:      summary: List all pets      operationId: listPets      tags:        - pets      parameters:        - name: limit          in: query          description: How many items to return at one time (max 100)          required: false          type: integer          format: int32      responses:        200:          description: An paged array of pets          headers:            x-next:              type: string              description: A link to the next page of responses          schema:            $ref: Pets        default:          description: unexpected error          schema:            $ref: Error    post:      summary: Create a pet      operationId: createPets      tags:        - pets      responses:        201:          description: Null response        default:          description: unexpected error          schema:            $ref: Error  /pets/{petId}:    get:      summary: Info for a specific pet      operationId: showPetById      tags:        - pets      parameters:        - name: petId          in: path          description: The id of the pet to retrieve          type: string      responses:        200:          description: Expected response to a valid request          schema:            $ref: Pets        default:          description: unexpected error          schema:            $ref: Errordefinitions:  Pet:    required:      - id      - name    properties:      id:        type: integer        format: int64      name:        type: string      tag:        type: string  Pets:    type: array    items:      $ref: Pet  Error:    required:      - code      - message    properties:      code:        type: integer        format: int32      message:        type: string; line: 1, column: 8]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2300)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1459)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:683)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3090)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3036)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1818)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:122)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:58)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:34)
	at com.wordnik.swagger.codegen.Codegen.main(Codegen.java:87)
java.lang.RuntimeException: missing swagger input or config!
	at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:31)
	at com.wordnik.swagger.codegen.Codegen.main(Codegen.java:99)
```

Did I miss something ?

Regards,
BQ.

**Comment by fehguy** [comment]
Howdy, there was a bug in 2.1.2-M2 that was causing this.  Please grab develop_2.0 and run:

```
mvn clean package
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -l java -i https://raw.githubusercontent.com/swagger-api/swagger-spec/master/examples/v2.0/yaml/petstore.yaml -o foo
```

You'll see it correctly generating in the `foo` directory.  Note the syntax is slightly different from before.

**Comment by sent1nel** [comment]
I just checked out develop_2.0, same behavior

`com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'swagger': was expecting ('true', 'false' or 'null')`

**Comment by webron** [comment]
@sent1nel - got a Swagger definition to share?

**Comment by sent1nel** [comment]
Actually, yes: https://github.com/open311/swagger-open311/blob/master/open311-georeporter.yaml

**Comment by fehguy** [comment]
OK looks like different line breaks.  Will get this fixed.

**Comment by fehguy** [comment]
OK this has been (re) fixed.  You can build locally or download 1.0.7-SNAPSHOT from sonatype-snapshots.

**Comment by fehguy** [comment]
Deployed to 1.0.7 in maven central.

**Comment by zxtwonder** [comment]
We are hitting the same issue using swagger-codegen:2.2.1 with swagger-parser:1.0.22 and swagger-compat-spec-parser:1.0.22. Looking at the exception stack trace and the source files, it seems that SwaggerCompatConverter.readResourceListing always tries to parse the input spec as a JSON file and therefore causes jackson to throw when the input is actually a yaml file.

This only happens with the org.detoeuf.swagger-codegen gradle plugin. swagger-codegen-cli-2.2.1.jar -i works as expected.
