### ISSUE TITLE
java.lang.NoSuchMethodError:

### ISSUE THREAD

**Issue by somisettyv** [swagger-api/swagger-parser#402]
I am getting the following error while parsing, is there any specific Jackson parser version I have to include in my POM.xml?

Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JsonNode.getNodeType()Lcom/fasterxml/jackson/databind/node/JsonNodeType;
	at io.swagger.parser.util.SwaggerDeserializer.parseRoot(SwaggerDeserializer.java:45)
	at io.swagger.parser.util.SwaggerDeserializer.deserialize(SwaggerDeserializer.java:36)
	at io.swagger.parser.Swagger20Parser.convertToSwagger(Swagger20Parser.java:128)
	at io.swagger.parser.Swagger20Parser.read(Swagger20Parser.java:97)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:64)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:52)
	at com.helloworld.service.SwaggerParserNew.main(SwaggerParserNew.java:14)

**Comment by fehguy** [comment]
2.8.x is required by swagger-core

https://github.com/swagger-api/swagger-core/blob/master/pom.xml#L494
