### ISSUE TITLE
enum Method missing TRACE

### ISSUE THREAD

**Issue by Sayi** [swagger-api/swagger-parser#487]
A request‘s method is trace, it throws exception:

```
java.lang.NullPointerException
	at io.swagger.parser.SwaggerCompatConverter.convertOperation(SwaggerCompatConverter.java:411)
	at io.swagger.parser.SwaggerCompatConverter.convert(SwaggerCompatConverter.java:571)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:176)	
```
So json string(contains trace method) converts to ApiDeclaration, the method field is null.

**Comment by webron** [comment]
TRACE is not a supported HTTP verb in Swagger 2.0. The next version adds support to it.
