### ISSUE TITLE
OpenAPI v2 converter - NullPointerException converting server URL when schemes is absent

### ISSUE THREAD

**Issue by benken-parasoft** [swagger-api/swagger-parser#518]
Converting from v2 fails if the v2 Swagger does not have "schemes".  According to Swagger v2 spec "schemes" is optional.  In addition to fixing the NullPointerException, the converter should also observe the part of the v2 spec that says "If the schemes is not included, the default scheme to be used is the one used to access the Swagger definition itself."

Reproduced using 2.0 branch:
```
java.lang.NullPointerException
	at io.swagger.parser.v2.SwaggerConverter.convert(SwaggerConverter.java:213)
	at io.swagger.parser.v2.SwaggerConverter.convert(SwaggerConverter.java:97)
	at io.swagger.parser.v2.SwaggerConverter.readLocation(SwaggerConverter.java:48)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:18)
```

**Comment by benken-parasoft** [comment]
This was fixed by https://github.com/swagger-api/swagger-parser/commit/8e18db82e97d1e4a8ca0e4df3fb4455949f05e97

Thanks again!
