### ISSUE TITLE
ClassCastException converting object with property of type array

### ISSUE THREAD

**Issue by gdombiak** [swagger-api/swagger-parser#525]
Hi,

I'm trying out the conversion from Swagger v2 to OpenAPI v3. I'm using latest code in branch 2.0 (commit 6df494cbea263c0ab17503f1e10cec877943f436). 

This is the exception I'm hitting:
```
java.lang.ClassCastException: io.swagger.oas.models.media.Schema cannot be cast to io.swagger.oas.models.media.ArraySchema
	at io.swagger.parser.v2.SwaggerConverter.lambda$convert$7(SwaggerConverter.java:784)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at io.swagger.parser.v2.SwaggerConverter.convert(SwaggerConverter.java:782)
	at io.swagger.parser.v2.SwaggerConverter.convert(SwaggerConverter.java:697)
	at io.swagger.parser.v2.SwaggerConverter.convert(SwaggerConverter.java:516)
	at io.swagger.parser.v2.SwaggerConverter.convert(SwaggerConverter.java:460)
	at io.swagger.parser.v2.SwaggerConverter.convert(SwaggerConverter.java:157)
	at io.swagger.parser.v2.SwaggerConverter.readContents(SwaggerConverter.java:66)
	at io.swagger.parser.test.V2ConverterTest.testIssue(V2ConverterTest.java:51)
```

This is the Swagger 2 that I'm trying to convert:
```
swagger: '2.0'
info:
  title: Some title
  version: ''
paths:
  "/some/thing":
    post:
      responses:
        '200':
          description: OK
          headers: {}
          schema:
            type: "object"
            properties:
              validations:
                type: "array"
                items:
                  type: "string"
      produces:
        - application/json
```

Code of the sample test is:
 ```
       SwaggerConverter converter = new SwaggerConverter();
        String swaggerAsString = new String(Files.readAllBytes(Paths.get(getClass().getClassLoader().getResource("issue.yaml").toURI())));
        SwaggerParseResult result = converter.readContents(swaggerAsString, null, null);
```

Let me know if you need any other information. I do not see an issue related to this or a PR pending for this. Is this a known issue? Anyone working on this? I can dig deeper to find root cause and maybe create a PR if there is interest.

Thanks,
Gaston

**Comment by webron** [comment]
@gdombiak - thanks for reporting, should be fixed now.

**Comment by gdombiak** [comment]
Thanks Ron for the blazing fast fix. :)

**Comment by webron** [comment]
I'm sure there are other issues - please file anything you find. I expect to push some more fixes in the next day or so. Most issues are around examples and formData parameter conversion.

**Comment by gdombiak** [comment]
Sure thing Ron. I will file a suggestion to make it easier to migrate from old swagger parser to new one. It's a tiny thing.

After updating I noticed a compilation error in OpenAPIDeserializer (seems unrelated to your commit) but I guess it might be due to my local environment. Around line 877 I had to add some .toString() to make it compile. If you see the same in your environment I can file an issue. If not I guess it was my local env switching between branches or something.
```
        if (StringUtils.isBlank(value)) {
            encoding.setStyle(Encoding.StyleEnum.FORM.toString());
        } else {
            if (value.equals(Encoding.StyleEnum.FORM.toString())) {
                encoding.setStyle(Encoding.StyleEnum.FORM.toString());
            } else if (value.equals(Encoding.StyleEnum.DEEP_OBJECT.toString())) {
                encoding.setStyle(Encoding.StyleEnum.DEEP_OBJECT.toString());
            } else if (value.equals(Encoding.StyleEnum.PIPE_DELIMITED.toString())) {
                encoding.setStyle(Encoding.StyleEnum.PIPE_DELIMITED.toString());
            } else if (value.equals(Encoding.StyleEnum.SPACE_DELIMITED.toString())) {
                encoding.setStyle(Encoding.StyleEnum.SPACE_DELIMITED.toString());
            } else {
                result.invalidType(location, "style", "string", node);
            }
        }
```

Thanks,
Gaston

**Comment by webron** [comment]
That's due to a faulty swagger-core SNAPSHOT. If you try to compile again, forcing downloads (-U), it should compile fine.
