### ISSUE TITLE
SwaggerCompatConverter does not parse local file correctly

### ISSUE THREAD

**Issue by fno2010** [swagger-api/swagger-parser#542]
For some reason, I am using swagger 1.2 to specify my api. And when I use swagger-parser to parse my resource list file in the local machine, I get the following error:

```
[main] ERROR io.swagger.parser.SwaggerCompatConverter - failed to read api declaration         
java.io.FileNotFoundException: null/https:/github.com/openalto/alto-swagger/raw/spec/api/ext/1.2/query.json (No such file or directory)                                                       
        at java.io.FileInputStream.open0(Native Method)                                        
        at java.io.FileInputStream.open(FileInputStream.java:195)                              
        at java.io.FileInputStream.<init>(FileInputStream.java:138)                            
        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:756)           
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2447)        
        at io.swagger.parser.SwaggerCompatConverter.readDeclaration(SwaggerCompatConverter.java:490)                                                                                          
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:169)      
        at io.swagger.parser.SwaggerCompatConverter.readWithInfo(SwaggerCompatConverter.java:87)                                                                                              
        at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:41)                 
        at io.swagger.codegen.cmd.Validate.run(Validate.java:25)                               
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

My resource list file is like following:

``` json
{
  "swaggerVersion": "1.2",
  "apiVersion": "0.1.1-oas1.2",
  "info": {
    "title": "Unicorn API",
    "description": "Cross-domain path and resource discovery"
  },
  "apis": [
    {
      "path": "https://github.com/openalto/alto-swagger/raw/spec/api/ext/1.2/query.json",
      "description": "Operations about path query and resource query"
    }
  ]
}
```

I think [here (SwaggerCompatConverter.java#L139)](https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java#L139) is the reason. The legacy swagger parser will parse api path as the remote url only when the input resource list file is also a remote url. I think it is not the right way.

Can we fix this issue?

**Comment by webron** [comment]
Hi @fno2010, sorry for the delayed reply.

Your API definition is actually invalid. The `path` needs to be a relative URL, not a full one, according to the spec. Take a look at https://github.com/OAI/OpenAPI-Specification/blob/master/versions/1.2.md#aePath. You'd need to fix your API definition before moving forward.
