### ISSUE TITLE
Swagger 2.0 (Petstore) file parsing fails

### ISSUE THREAD

**Issue by ArulPrakas** [swagger-api/swagger-parser#55]
Parser used:
```xml
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-parser</artifactId>
            <version>1.0.5</version>
        </dependency>
```

File : http://petstore.swagger.io/v2/swagger.json

Error:
reading from http://petstore.swagger.io/v2/swagger.json
com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: com.wordnik.swagger.models.ModelImpl["properties"]) (through reference chain: com.wordnik.swagger.models.Swagger["definitions"])

**Comment by webron** [comment]
Have you tried the latest?

**Comment by ArulPrakas** [comment]
Not yet. do you mean 1.0.7?  Just curios to know how versions are defined for parser? Will fixes be backported to older versions? how frequently the new versions will get updated?

**Comment by webron** [comment]
dot versions are meant to be fixes and should be backwards compatible. We release new versions based on issues and requirements, there's no predefined schedule. 

I'd suggest always trying to upgrade the the latest to see if it solves the issue you have, and if not, we'll do our best to look into it.

**Comment by ArulPrakas** [comment]
Tried with 1.0.7 and still issue exits. Complete stack trace:

reading from http://petstore.swagger.io/v2/swagger.json
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: com.wordnik.swagger.models.ModelImpl["properties"]) (through reference chain: com.wordnik.swagger.models.Swagger["definitions"])
java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: com.wordnik.swagger.models.ModelImpl["properties"]) (through reference chain: com.wordnik.swagger.models.Swagger["definitions"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:2759)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:2685)
	at io.swagger.parser.Swagger20Parser.convertToSwagger(Swagger20Parser.java:57)
	at io.swagger.parser.Swagger20Parser.read(Swagger20Parser.java:31)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:25)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:14)
	at com.aris.apiportal.importer.extn.swagger.SwaggerImporter.importSwagger(SwaggerImporter.java:23)
	at com.aris.apiportal.importer.extn.swagger.SwaggerImporter.main(SwaggerImporter.java:88)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: com.wordnik.swagger.models.ModelImpl["properties"]) (through reference chain: com.wordnik.swagger.models.Swagger["definitions"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:232)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:197)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1415)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:2754)
	... 7 more
Caused by: java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: com.wordnik.swagger.models.ModelImpl["properties"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:2759)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:2685)
	at com.wordnik.swagger.util.ModelDeserializer.deserialize(ModelDeserializer.java:55)
	at com.wordnik.swagger.util.ModelDeserializer.deserialize(ModelDeserializer.java:16)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:449)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:311)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	... 9 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: com.wordnik.swagger.models.ModelImpl["properties"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:232)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:197)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1415)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:2754)
	... 18 more
Caused by: java.lang.ClassCastException: com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode
	at com.wordnik.swagger.util.PropertyDeserializer.propertyFromNode(PropertyDeserializer.java:75)
	at com.wordnik.swagger.util.PropertyDeserializer.deserialize(PropertyDeserializer.java:22)
	at com.wordnik.swagger.util.PropertyDeserializer.deserialize(PropertyDeserializer.java:15)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:449)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:311)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	... 20 more

**Comment by benken-parasoft** [comment]
This problem looks to be already fixed in 1.0.7.

I no longer get the problem after updating to 1.0.7.  I notice the new 1.0.7 version also depends on the new swagger-core-1.5.2-M2 instead of the older M1.  I think at least part of the problem may have been in swagger-core or swagger-models, not swagger-parser specifically.  I am building my project with maven and so I just let maven pull in the correct dependencies for swagger-parser automatically.

This is easy to test with a simple java main().  I get no error with 1.0.7 but did with an older version:

import io.swagger.parser.*;
public class Test {
    public static void main(String[] args) {
        new SwaggerParser().read("http://petstore.swagger.io/v2/swagger.json");
   }
}

**Comment by benken-parasoft** [comment]
I also tried the YAML version and get no error with that either: http://petstore.swagger.io/v2/swagger.yaml

**Comment by webron** [comment]
Thanks for providing the input. Closing for now.
