### ISSUE TITLE
UTF-8 YAML document fails to parse with cryptic message

### ISSUE THREAD

**Issue by jimschubert** [swagger-api/swagger-parser#564]
I'm copying this issue verbatim from swagger-api/swagger-codegen#6848

I'm able to repro the exception when the document is saved as YAML, but I have no error when the document is saved as JSON (exported from Swagger Editor as JSON). I'm able to successfully generate via swagger-codegen against other YAML/JSON documents, and Swagger Editor doesn't display any validation errors on the referenced document.

I've attempted after converting from CRLF to LF, and saving in a variety of different encodings (with and without BOM) but this specific YAML document fails.

/cc original reporter @GioviQ

---

## Description

Based on the output
```
[main] ERROR io.swagger.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('#' (code 35)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
at APIREST+Corrispettivi+gestionali.yaml; line: 1, column: 2]
```

I don't know how to fix yaml file

I tried to add # before $ref with no success.

## Swagger-codegen version

2.2.3

## Swagger declaration file content or url

http://www.agenziaentrate.gov.it/wps/wcm/connect/9ce8ea74-ebc4-4723-8494-a8d0227004d2/APIREST+Corrispettivi+gestionali.yaml?MOD=AJPERES&CACHEID=9ce8ea74-ebc4-4723-8494-a8d0227004d2

## Command line used for generation

-l android -o "D:\temp" --api-package "it.gov.agenziaentrate.api"

**Comment by jimschubert** [comment]
For reference, here's the full command I used and stack trace I received (after converting to LF and removing comments at the top of the file):

```
$ java $JAVA_OPTS -jar /path/swagger-codegen-cli.jar generate \
   -l android -o ./out -i swagger.yaml --api-package "it.gov.agenziaentrate.api"
[main] INFO io.swagger.parser.Swagger20Parser - reading from swagger.yaml
[main] INFO io.swagger.parser.Swagger20Parser - reading from swagger.yaml
[main] ERROR io.swagger.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'swagger': was expecting ('true', 'false' or 'null')
 at [Source: swagger.yaml; line: 1, column: 9]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3528)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2686)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3850)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2447)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:189)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:116)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:75)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:431)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:283)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:715)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

**Comment by gracekarina** [comment]
Hi, @jimschubert, @GioviQ it seems like there is a TAB (t) in line 124 of the file, I have removed it and it generates ok, and also parses ok. 
Please let me know if this solved your issue
