### ISSUE TITLE
Local references to path items are not resolved

### ISSUE THREAD

**Issue by ikurovsky** [swagger-api/swagger-parser#608]
If a path item contains a reference to another path item defined in the same document then parser does not resolve the reference.

For example, consider a simple Swagger 2.0 spec:

```yml
swagger: '2.0'
info:
  version: 0.0.0
  title: Path item $ref test

paths:
  /foo:
    get:
      responses:
        200:
          description: OK

  /foo2:
    $ref: '#/paths/~1foo'
```

This spec is succesfully recognized by the Swagger Editor, but is not parsed by the SwaggerParser (version 1.0.33) which throws exception:
```java
java.lang.NullPointerException
	at io.swagger.parser.processors.PathsProcessor.updateLocalRefs(PathsProcessor.java:107)
	at io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:84)
	at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:50)
	at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:129)
	at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:121)
```

**Comment by ikurovsky** [comment]
It seems that the ResolverCache#loadInternalRef does not recognize the case when internal reference is a path item and attempts to load a definition instead.

**Comment by gracekarina** [comment]
Hi @ikurovsky  give it a try and let us know how it goes. Happy Holidays!

**Comment by ikurovsky** [comment]
Hi @gracekarina, it looks good to me, thank you. Happy Holidays!
