### ISSUE TITLE
Unable to load RELATIVE ref, $ref using dot-segments

### ISSUE THREAD

**Issue by sfreeman422** [swagger-api/swagger-parser#644]
Getting the below when trying to use $refs that include dot-segments ( . or ../). 

```
Exception in thread "main" java.lang.RuntimeException: Unable to load RELATIVE ref: ../../common/core/simpleIDType_v02.json#
        at io.swagger.parser.util.RefUtils.readExternalRef(RefUtils.java:146)
        at io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:112)
        at io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(ExternalRefProcessor.java:37)
        at io.swagger.parser.processors.ExternalRefProcessor.processRefProperty(ExternalRefProcessor.java:132)
        at io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(ExternalRefProcessor.java:102)
        at io.swagger.parser.processors.PropertyProcessor.processRefProperty(PropertyProcessor.java:34)
        at io.swagger.parser.processors.PropertyProcessor.processProperty(PropertyProcessor.java:21)
        at io.swagger.parser.processors.PropertyProcessor.processArrayProperty(PropertyProcessor.java:52)
        at io.swagger.parser.processors.PropertyProcessor.processProperty(PropertyProcessor.java:23)
        at io.swagger.parser.processors.ResponseProcessor.processResponse(ResponseProcessor.java:21)
        at io.swagger.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:45)
        at io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:101)
        at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:50)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:67)
        at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:431)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:283)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.RuntimeException: Could not find ../../common/core/simpleIDType_v02.json# on the classpath
        at io.swagger.parser.util.ClasspathHelper.loadFileFromClasspath(ClasspathHelper.java:31)
        at io.swagger.parser.util.RefUtils.readExternalRef(RefUtils.java:141)
```

Dot segments appear to be valid in the $ref for JSON schema however, are not supported in the swagger-parser. It should be noted that I am making use of swagger-parser via swagger-codegen and attempting to generate Java with a schema that references local files. 

Folder structure is as follows: 
```
|- apis
  |- hr
    |- api
      |- schema
         - foo.json
  |- core
    |- codeType
      |- bar.json
```

The $ref for `bar.json` is listed inside of `foo.json` as `"$ref": "../../../core/codeType/bar.json#"` which appears to be in spec per [Swagger Docs](https://swagger.io/docs/specification/using-ref/).

If I restructure so that the files are included, all within the same directory, this is a non-issue however, existing directory structure over hundreds of APIs makes this difficult.

**Comment by slimane-deb** [comment]
@sfreeman422 just came by your issue, did you have a fix/ workaround for this?
