### ISSUE TITLE
Getting POM error on building the package

### ISSUE THREAD

**Issue by heather7532** [swagger-api/swagger-parser#654]
I'm no Maven expert and I'm getting the error below when trying to build swagger-parser.  I've tried this from Jenkins (output below) and from the command line with the same result.  I've also tried this from both within and outside of the corporate VPN I work in just to verify it is not some sort of local issue.  I would appreciate a little guidance.  I did notice the POM was modified in the last few weeks.

Started by user rg4311@csp.att.com
[DYSON] Dyson started swagger-parser
[EnvInject] - Loading node environment variables.
Building remotely on zlp23074.vci.att.com (maven local-docker-engine ansible docker mscatalog3) in workspace /home/m61407/node/sdt-eco.vci.att.com_19592/workspace/com.att.ipdd/swagger-parser
Parsing POMs
Established TCP socket on 27661
maven-agent.jar already up to date
classworlds.jar already up to date
maven-interceptor.jar already up to date
maven2.1-interceptor.jar already up to date
[swagger-parser] $ /opt/app/java/jdk/jdk180/bin/java -cp /home/m61407/node/sdt-eco.vci.att.com_19592/maven-agent.jar:/home/m61407/node/sdt-eco.vci.att.com_19592/classworlds.jar hudson.maven.agent.Main /opt/app/mvn221/apache-maven-2.2.1 /opt/app/m61407_node/sdt-eco.vci.att.com_19592/slave.jar /home/m61407/node/sdt-eco.vci.att.com_19592/maven-interceptor.jar 27661 /home/m61407/node/sdt-eco.vci.att.com_19592/maven2.1-interceptor.jar
<===[JENKINS REMOTING CAPACITY]===>channel started
Executing Maven:  -B -f /home/m61407/node/sdt-eco.vci.att.com_19592/workspace/com.att.ipdd/swagger-parser/pom.xml -e -V package
+ Error stacktraces are turned on.
Apache Maven 2.2.1 (r801777; 2009-08-06 15:16:01-0400)
Java version: 1.8.0_121
Java home: /opt/app/java/jdk/jdk180_121/64bit/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux" version: "3.10.0-693.2.2.el7.x86_64" arch: "amd64" Family: "unix"
[INFO] Scanning for projects...
[INFO] Reactor build order: 
[INFO]   swagger-parser-project
[INFO]   swagger-parser
[INFO]   swagger-compat-spec-parser
[INFO] ------------------------------------------------------------------------
[INFO] Building swagger-parser-project
[INFO]    task-segment: [package]
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: org.apache.maven.plugins:maven-site-plugin
POM Location: /home/m61407/.m2/repository/org/apache/maven/plugins/maven-site-plugin/2.0-beta-7/maven-site-plugin-2.0-beta-7.pom

Reason: Not a v4.0.0 POM. for project org.apache.maven.plugins:maven-site-plugin at /home/m61407/.m2/repository/org/apache/maven/plugins/maven-site-plugin/2.0-beta-7/maven-site-plugin-2.0-beta-7.pom

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Unable to build project for plugin 'org.apache.maven.plugins:maven-site-plugin': Not a v4.0.0 POM. for project org.apache.maven.plugins:maven-site-plugin at /home/m61407/.m2/repository/org/apache/maven/plugins/maven-site-plugin/2.0-beta-7/maven-site-plugin-2.0-beta-7.pom
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(DefaultLifecycleExecutor.java:1557)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getMojoDescriptor(DefaultLifecycleExecutor.java:1851)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.bindLifecycleForPackaging(DefaultLifecycleExecutor.java:1311)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.constructLifecycleMappings(DefaultLifecycleExecutor.java:1275)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:534)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
	at org.apache.maven.lifecycle.LifecycleExecutorInterceptor.execute(LifecycleExecutorInterceptor.java:65)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at hudson.maven.agent.Main.launch(Main.java:205)
	at hudson.maven.MavenBuilder.call(MavenBuilder.java:153)
	at hudson.maven.Maven2Builder.call(Maven2Builder.java:79)
	at hudson.maven.Maven2Builder.call(Maven2Builder.java:55)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.plugin.InvalidPluginException: Unable to build project for plugin 'org.apache.maven.plugins:maven-site-plugin': Not a v4.0.0 POM. for project org.apache.maven.plugins:maven-site-plugin at /home/m61407/.m2/repository/org/apache/maven/plugins/maven-site-plugin/2.0-beta-7/maven-site-plugin-2.0-beta-7.pom
	at org.apache.maven.plugin.DefaultPluginManager.checkRequiredMavenVersion(DefaultPluginManager.java:293)
	at org.apache.maven.plugin.DefaultPluginManager.verifyVersionedPlugin(DefaultPluginManager.java:205)
	at org.apache.maven.plugin.DefaultPluginManager.verifyPlugin(DefaultPluginManager.java:184)
	at org.apache.maven.plugin.DefaultPluginManager.loadPluginDescriptor(DefaultPluginManager.java:1642)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(DefaultLifecycleExecutor.java:1540)
	... 29 more
Caused by: org.apache.maven.project.InvalidProjectModelException: Not a v4.0.0 POM. for project org.apache.maven.plugins:maven-site-plugin at /home/m61407/.m2/repository/org/apache/maven/plugins/maven-site-plugin/2.0-beta-7/maven-site-plugin-2.0-beta-7.pom
	at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1599)
	at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1571)
	at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:562)
	at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:251)
	at org.apache.maven.plugin.DefaultPluginManager.checkRequiredMavenVersion(DefaultPluginManager.java:277)
	... 33 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Wed Feb 28 11:30:23 EST 2018
[INFO] Final Memory: 16M/964M
[INFO] ------------------------------------------------------------------------
channel stopped
[DYSON] Dyson successfully completed
Finished: FAILURE

**Comment by webron** [comment]
It looks like you're using an old version of Maven. You need at least version 3.0.3.

**Comment by heather7532** [comment]
I made that change and it is still complaining about the POM.  I also attached the output trying it from the command line.

Started by user rg4311@csp.att.com
[DYSON] Dyson started swagger-parser
[EnvInject] - Loading node environment variables.
Building remotely on zlp23074.vci.att.com (maven local-docker-engine ansible docker mscatalog3) in workspace /home/m61407/node/sdt-eco.vci.att.com_19592/workspace/com.att.ipdd/swagger-parser
Parsing POMs
Established TCP socket on 14583
maven33-agent.jar already up to date
maven33-interceptor.jar already up to date
maven3-interceptor-commons.jar already up to date
[swagger-parser] $ /opt/app/java/jdk/jdk180/bin/java -cp /home/m61407/node/sdt-eco.vci.att.com_19592/maven33-agent.jar:/opt/app/mvn339/apache-maven-3.3.9/boot/plexus-classworlds-2.5.2.jar:/opt/app/mvn339/apache-maven-3.3.9/conf/logging jenkins.maven3.agent.Maven33Main /opt/app/mvn339/apache-maven-3.3.9 /opt/app/m61407_node/sdt-eco.vci.att.com_19592/slave.jar /home/m61407/node/sdt-eco.vci.att.com_19592/maven33-interceptor.jar /home/m61407/node/sdt-eco.vci.att.com_19592/maven3-interceptor-commons.jar 14583
<===[JENKINS REMOTING CAPACITY]===>channel started
Executing Maven:  -B -f /home/m61407/node/sdt-eco.vci.att.com_19592/workspace/com.att.ipdd/swagger-parser/pom.xml -e -V -X package
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /opt/app/mvn339/apache-maven-3.3.9
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /opt/app/java/jdk/jdk180_121/64bit/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-693.2.2.el7.x86_64", arch: "amd64", family: "unix"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /opt/app/mvn339/apache-maven-3.3.9/conf/settings.xml
[DEBUG] Reading user settings from /home/m61407/.m2/settings.xml
[DEBUG] Reading global toolchains from /opt/app/mvn339/apache-maven-3.3.9/conf/toolchains.xml
[DEBUG] Reading user toolchains from /home/m61407/.m2/toolchains.xml
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] swagger-parser-project
[INFO] swagger-parser
[INFO] swagger-compat-spec-parser
[DYSON] Dyson started io.swagger:swagger-parser-project
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building swagger-parser-project 1.0.35-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.apache.maven.plugins:maven-enforcer-plugin:jar:1.0-beta-1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[DYSON] Dyson successfully completed
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] swagger-parser-project ............................. FAILURE [  0.547 s]
[INFO] swagger-parser ..................................... SKIPPED
[INFO] swagger-compat-spec-parser ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.750 s
[INFO] Finished at: 2018-02-28T12:41:51-05:00
[INFO] Final Memory: 24M/964M
[INFO] ------------------------------------------------------------------------
Waiting for Jenkins to finish collecting data[ERROR] Plugin org.apache.maven.plugins:maven-enforcer-plugin:1.0-beta-1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-enforcer-plugin:jar:1.0-beta-1: 1 problem was encountered while building the effective model
[ERROR] [FATAL] Non-parseable POM /home/m61407/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/1.0-beta-1/maven-enforcer-plugin-1.0-beta-1.pom: unexpected markup <!d (position: START_DOCUMENT seen <!d... @1:3)  @ line 1, column 3
[ERROR] -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin org.apache.maven.plugins:maven-enforcer-plugin:1.0-beta-1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-enforcer-plugin:jar:1.0-beta-1
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:117)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getPluginDescriptor(DefaultMavenPluginManager.java:179)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getMojoDescriptor(DefaultMavenPluginManager.java:284)
	at org.apache.maven.plugin.DefaultBuildPluginManager.getMojoDescriptor(DefaultBuildPluginManager.java:241)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleMappingDelegate.calculateLifecycleMappings(DefaultLifecycleMappingDelegate.java:110)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateLifecycleMappings(DefaultLifecycleExecutionPlanCalculator.java:266)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateMojoExecutions(DefaultLifecycleExecutionPlanCalculator.java:217)

	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:127)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:145)
	at org.apache.maven.lifecycle.internal.builder.BuilderCommon.resolveBuildPlan(BuilderCommon.java:96)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:109)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[JENKINS] Archiving /home/m61407/node/sdt-eco.vci.att.com_19592/workspace/com.att.ipdd/swagger-parser/modules/swagger-parser/pom.xml to io.swagger/swagger-parser/1.0.35-SNAPSHOT/swagger-parser-1.0.35-SNAPSHOT.pom
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.jvnet.hudson.maven3.launcher.Maven33Launcher.main(Maven33Launcher.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at jenkins.maven3.agent.Maven33Main.launch(Maven33Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.apache.maven.plugins:maven-enforcer-plugin:jar:1.0-beta-1
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:338)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:287)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:103)
	... 38 more
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model
[FATAL] Non-parseable POM /home/m61407/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/1.0-beta-1/maven-enforcer-plugin-1.0-beta-1.pom: unexpected markup <!d (position: START_DOCUMENT seen <!d... @1:3)  @ line 1, column 3

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:197)
	at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:579)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:273)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:320)
	... 41 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
[JENKINS] Archiving /home/m61407/node/sdt-eco.vci.att.com_19592/workspace/com.att.ipdd/swagger-parser/modules/swagger-compat-spec-parser/pom.xml to io.swagger/swagger-compat-spec-parser/1.0.35-SNAPSHOT/swagger-compat-spec-parser-1.0.35-SNAPSHOT.pom
[JENKINS] Archiving /home/m61407/node/sdt-eco.vci.att.com_19592/workspace/com.att.ipdd/swagger-parser/pom.xml to io.swagger/swagger-parser-project/1.0.35-SNAPSHOT/swagger-parser-project-1.0.35-SNAPSHOT.pom
channel stopped
[DYSON] Dyson successfully completed
Finished: FAILURE


[mvn-output.txt](https://github.com/swagger-api/swagger-parser/files/1768204/mvn-output.txt)

**Comment by webron** [comment]
That's a different issue. It seems to not be able to connect to sonatype. Probably a firewall or something in the way.

**Comment by heather7532** [comment]
That was it.  I had to get the proper settings for the proxy in settings.xml.  Thank you for answering!
