### ISSUE TITLE
Recent regression in 2.0-branch when converting Swagger 2.0 specification

### ISSUE THREAD

**Issue by mkauf** [swagger-api/swagger-parser#672]
[This swagger 2.0 specification](https://raw.githubusercontent.com/OpenBankingUK/payment-initiation-api-spec/master/dist/v1.1/payment-initiation-swagger.json) can be successfully converted with swagger-parser version 2.0.0-rc3, but it gives a ``NullPointerException`` on the current 2.0 branch:

```
Exception in thread "main" java.lang.NullPointerException
	at io.swagger.models.utils.PropertyModelConverter.modelToProperty(PropertyModelConverter.java:43)
	at io.swagger.models.Response.getSchema(Response.java:58)
	at io.swagger.v3.parser.converter.SwaggerInventory.process(SwaggerInventory.java:179)
	at io.swagger.v3.parser.converter.SwaggerInventory.process(SwaggerInventory.java:171)
	at io.swagger.v3.parser.converter.SwaggerInventory.process(SwaggerInventory.java:147)
	at io.swagger.v3.parser.converter.SwaggerInventory.process(SwaggerInventory.java:109)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:135)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:91)
	at Converter.main(Converter.java:22)
```

I use ``io.swagger.v3.parser.converter.SwaggerConverter.readLocation()`` to convert this specification.

It works again if I edit the pom.xml and change the propery "swagger-parser-v2-version" from "1.0.35-SNAPSHOT" to "1.0.34".

**Comment by ralphdoe** [comment]
Solved! The solution was merged on April 8. Thanks!
