### ISSUE TITLE
NullPointerException at io.swagger.v3.parser.converter.SwaggerConverter.convertOauth2SecurityScheme(SwaggerConverter.java:320)

### ISSUE THREAD

**Issue by garydgregory** [swagger-api/swagger-parser#732]
```
java.lang.NullPointerException
	at io.swagger.v3.parser.converter.SwaggerConverter.convertOauth2SecurityScheme(SwaggerConverter.java:320)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:279)
	at io.swagger.v3.parser.converter.SwaggerConverter.lambda$convert$2(SwaggerConverter.java:222)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:222)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:93)
	at io.swagger.v3.parser.OpenAPIV3Parser.read(OpenAPIV3Parser.java:90)
	at io.swagger.v3.parser.OpenAPIV3Parser.read(OpenAPIV3Parser.java:78)
```
while parsing:
```
swagger: '2.0'
schemes:
  - https
host: airport-web.appspot.com
basePath: /_ah/api
info:
  description: Get name and website-URL for airports by ICAO code. Covered airports are mostly in Germany.
  title: airportsapi
  version: v1
  x-apisguru-categories:
    - transport
  x-logo:
    url: 'https://user-images.githubusercontent.com/21603/37955263-098e5b38-31a0-11e8-96fd-5755b16341e3.png'
  x-origin:
    - format: swagger
      url: 'https://airport-web.appspot.com/api/docs/swagger.json'
      version: '2.0'
  x-providerName: airport-web.appspot.com
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  google_id_token:
    authorizationUrl: ''
    flow: implicit
    type: oauth2
    x-google-issuer: accounts.google.com
    x-google-jwks_uri: 'https://www.googleapis.com/oauth2/v1/certs'
paths:
  '/airportsapi/v1/airports/{icao_code}':
    get:
      operationId: AirportApi_getAirport
      parameters:
        - in: path
          name: icao_code
          required: true
          type: string
      responses:
        '200':
          description: A successful response
          schema:
            $ref: '#/definitions/ApiEndpointsAirportResponse'
definitions:
  ApiEndpointsAirportResponse:
    properties:
      ICAO:
        type: string
      last_update:
        type: string
      name:
        type: string
      url:
        type: string
    type: object
```

**Comment by ymohdriz** [comment]
Hi team,

Raised a PR for this issue - https://github.com/swagger-api/swagger-parser/pull/736

Thanks,
Mohammed

**Comment by ralphdoe** [comment]
Review and Closed! Thanks @ymohdriz!
