### ISSUE TITLE
OpenAPI v2 converter: NullPointerException when info section is missing

### ISSUE THREAD

**Issue by jmini** [swagger-api/swagger-parser#755]
With a OAS2 Spec like this:

```
swagger: '2.0'
host: petstore.swagger.io
basePath: /v2
schemes:
  - http
paths:
  /ping:
    post:
      summary: test
      description: 'test it'
      operationId: pingOp
      responses:
        '200':
          description: OK
```

There is a NullPointerException during conversion OAS2 -> OAS3:

```
Exception in thread "main" java.lang.NullPointerException
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:422)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:144)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:93)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:19)
```

**Comment by jmini** [comment]
This is fixed in PR https://github.com/swagger-api/swagger-parser/pull/753 by @bmordue

**Comment by ralphdoe** [comment]
Reviewed and merged! Thanks!
