### ISSUE TITLE
OpenAPI v2 Converter: Null pointer exception when schema field is missing in body parameter

### ISSUE THREAD

**Issue by ymohdriz** [swagger-api/swagger-parser#756]
With an OAS spec like this:

[swagger.txt](https://github.com/swagger-api/swagger-parser/files/2172061/swagger.txt)

Got the below NPE:

java.lang.NullPointerException
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:1079)
	at io.swagger.v3.parser.converter.SwaggerConverter.convertParameterToRequestBody(SwaggerConverter.java:707)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:533)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:488)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:203)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:93)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:19)
	at io.swagger.parser.OpenAPIParserTest.testSimple(OpenAPIParserTest.java:51)

Thanks,
Mohammed

**Comment by ralphdoe** [comment]
Merged!
