### ISSUE TITLE
OpenAPI v2 Converter: NPE when type is array and 'items' field is missing in array property

### ISSUE THREAD

**Issue by ymohdriz** [swagger-api/swagger-parser#762]
With an OAI spec like this
[issue-762.txt](https://github.com/swagger-api/swagger-parser/files/2172875/issue-762.txt)

Got null pointer exception as below
java.lang.NullPointerException
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:852)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:830)
	at io.swagger.v3.parser.converter.SwaggerConverter.lambda$convert$10(SwaggerConverter.java:1086)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:1085)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:215)
	at io.swagger.v3.parser.converter.SwaggerConverter.readContents(SwaggerConverter.java:107)
	at io.swagger.parser.test.V2ConverterTest.getConvertedOpenAPIFromJsonFile(V2ConverterTest.java:672)

Thanks,
Mohammed

**Comment by ralphdoe** [comment]
Merged!
