### ISSUE TITLE
Open API V2 Converter: NPE when flow field is missing in securityDefinitions

### ISSUE THREAD

**Issue by ymohdriz** [swagger-api/swagger-parser#786]
With an OAI spec like this:
[securityExample.txt](https://github.com/swagger-api/swagger-parser/files/2261236/securityExample.txt)

Got a null pointer exception as below:
java.lang.NullPointerException
	at io.swagger.v3.parser.converter.SwaggerConverter.convertOauth2SecurityScheme(SwaggerConverter.java:301)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:279)
	at io.swagger.v3.parser.converter.SwaggerConverter.lambda$convert$2(SwaggerConverter.java:222)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:222)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:93)

Thanks,
Mohammed

**Comment by ymohdriz** [comment]
Closing this issue as related PR is merged
