### ISSUE TITLE
`SwaggerParser#read`'s Behavior with URI 

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-parser#81]
_From @kevinmeredith on August 26, 2015 15:49_

With `"io.swagger" % "swagger-parser" % "1.0.10"`:

And the following code:

```
import io.swagger.parser.SwaggerParser
import io.swagger.models.Swagger
import java.net.URI

import scala.util.control.NonFatal

object SwaggerService {

  def getSwaggerObj(swaggerDoc: URI): Either[Throwable, Option[Swagger]] = {
    try {
      Right( Option( new SwaggerParser().read(swaggerDoc.toString) ) )
    }
    catch {
      case NonFatal(e) => Left(e)
    }
  }
```

I then ran it from Scala's REPL:

```
scala> new File("/Users/kevin/Workspace/Work/json_sandbox/petstore.json")
res7: java.io.File = /Users/kevin/Workspace/Work/json_sandbox/petstore.json

scala> res7.toURI
res8: java.net.URI = file:/Users/kevin/Workspace/Work/json_sandbox/petstore.json

scala> SwaggerService.getSwaggerObj(res8)
reading from file:/Users/kevin/Workspace/Work/json_sandbox/petstore.json
File 'file:/Users/kevin/Workspace/Work/json_sandbox/petstore.json' does not exist
reading from file:/Users/kevin/Workspace/Work/json_sandbox/petstore.json
File 'file:/Users/kevin/Workspace/Work/json_sandbox/petstore.json' does not exist
res9: Either[Throwable,Option[io.swagger.models.Swagger]] = Right(None)
```

However, if I cut out the `file:` from the URI's constructor's String argument, and then make a new `URI`, it works:

```
scala> new URI("/Users/kevin/Workspace/Work/json_sandbox/petstore.json")
res12: java.net.URI = /Users/kevin/Workspace/Work/json_sandbox/petstore.json

scala> SwaggerService.getSwaggerObj(res12)
reading from /Users/kevin/Workspace/Work/json_sandbox/petstore.json
res13: Either[Throwable,Option[io.swagger.models.Swagger]] = Right(Some(io.swagger.models.Swagger@657e4ba9))
```

Since a new `URI` can be created via [java.io.File#toURI](http://docs.oracle.com/javase/7/docs/api/java/io/File.html#toURI()), I would've expected my `File#toURI`-created URI to have worked here, but it didn't.

_Copied from original issue: swagger-api/swagger-spec#448_

**Comment by kevinmeredith** [comment]
Here's another test:

```
scala> import io.swagger.parser.SwaggerCompatConverter
import io.swagger.parser.SwaggerCompatConverter

scala> val file = new java.io.File("/Users/kevin/Workspace/myproject/src/test/resources/swagger_doc_v1.2.json")
file: java.io.File = /Users/kevin/Workspace/myproject/src/test/resources/swagger_doc_v1.2.json

scala> file.toURI
res0: java.net.URI = file:/Users/kevin/Workspace/myproject/src/test/resources/swagger_doc_v1.2.json

scala> new SwaggerCompatConverter().read(res0.toString)
java.io.FileNotFoundException: 
file:/Users/kevin/Workspace/myproject/src/test/resources/swagger_doc_v1.2.json (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:708)
    at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1861)
    at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:147)
    at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:82)
    at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:74)
```

Now, let's remove the `file:` prefix and try again:

```
scala> val filePathWithoutFilePrefix = res0.toString.drop(5)
filePathWithoutFilePrefix: String = /Users/kevin/Workspace/Work/myproject/src/test/resources/swagger_doc_v1.2.json

scala> new SwaggerCompatConverter().read(filePathWithoutFilePrefix)
...
res2: io.swagger.models.Swagger = io.swagger.models.Swagger@a682a8ca
```

**Comment by fehguy** [comment]
This should be supported now.
