### ISSUE TITLE
SwaggerCompatConverter()#read on v 1.2 Doc Showing 0 Paths

### ISSUE THREAD

**Issue by kevinmeredith** [swagger-api/swagger-parser#82]
Given the following Swagger doc:

```
$cat /Users/kevin/Workspace/Work/myproject/src/test/resources/swagger_doc_v1.2.json
{
  "apiVersion" : "1.0",
  "swaggerVersion" : "1.2",
  "basePath" : ".",
  "apis" : [
    {
      "path": "/fields",
      "description" : "Resource for fields"
    },
    {
      "path": "/plots",
      "description": "Operation about Plot resource"
    }
  ],
  "info" : {
    "title" : "Location",
    "description" : "Location apis"
  }
```

Using version `1.0.10`, I try to parse it using `SwaggerCompatConverter()#read`:

```
scala> uriPath
res4: String = /Users/kevin/Workspace/Work/myproject/src/test/resources/swagger_doc_v1.2.json

scala> new SwaggerCompatConverter().read(uriPath)
java.io.FileNotFoundException: /Users/kevin/Workspace/Work/myproject/src/test/resources/fields (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:708)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1861)
	at io.swagger.parser.SwaggerCompatConverter.readDeclaration(SwaggerCompatConverter.java:437)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:127)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:74)
java.io.FileNotFoundException: /Users/kevin/Workspace/Work/myproject/src/test/resources/plots (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
io.swagger.parser.SwaggerCompatConverter.readDeclaration(SwaggerCompatConverter.java:437)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:127)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:74)
res6: io.swagger.models.Swagger = io.swagger.models.Swagger@a682a8ca
```

And it shows **0 paths**:

```
scala> res6.getPaths
res8: java.util.Map[String,io.swagger.models.Path] = {}
```

Am I doing something wrong?

Thanks,
Kevin

**Comment by webron** [comment]
Where are your "/fields" and "/plots" files located?

**Comment by webron** [comment]
1.2 specs are multi-file definitions. If you don't have all the files, you don't have the full description of the API. In fact, the main file doesn't even describe any of the operations or models, so you'd end up having no paths.

**Comment by kevinmeredith** [comment]
OK - I'll close this ticket then. It was caused by my lack of understanding.

Thanks for the explanation!
