### ISSUE TITLE
NPE when the input open API file is empty

### ISSUE THREAD

**Issue by hemchan** [swagger-api/swagger-parser#872]
Hi team,

Thanks for the nice project.
I got an null pointer exception when using the empty file.

Below is the error:
1258 [main] ERROR io.swagger.parser.SwaggerCompatConverter - failed to read resource listing
java.lang.NullPointerException
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:213)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
	at io.swagger.parser.SwaggerCompatConverter.readWithInfo(SwaggerCompatConverter.java:94)
	at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:42)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:92)

Thanks,
Hemchand

**Comment by ymohdriz** [comment]
Hi HemChand,

I tried the scenario and it returns the expected null as the input file has no content.
What you have mentioned in this issue is the error log which can be avoided, let me raise a PR to avoid this NPE.

Thanks,
Mohamed Rizwan

**Comment by gracekarina** [comment]
fixed by #876
